name: Test NixOS Systems Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: nix-latest
    steps:
      - name: Setup SSH for private repository
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NIXOS_PRIVATE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Configure Git
        run: |
          git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"

      - name: Test flake check
        run: nix flake check --all-systems --no-build

      - name: Dry-run build all systems
        run: |
          echo "Testing all NixOS configurations..."
          systems=$(nix flake show --json 2>/dev/null | jq -r '.nixosConfigurations | keys[]')
          
          failed=0
          for system in $systems; do
            echo "::group::Testing $system"
            if nix build ".#nixosConfigurations.$system.config.system.build.toplevel" --dry-run --show-trace; then
              echo "✓ $system: OK"
            else
              echo "✗ $system: FAILED"
              failed=$((failed + 1))
            fi
            echo "::endgroup::"
          done
          
          if [ $failed -gt 0 ]; then
            echo "::error::$failed system(s) failed to build"
            exit 1
          fi
          
          echo "::notice::All systems validated successfully"

